name: Test Services

on:
  push:
    branches:
      - main
    paths:
      - 'services/**'
  workflow_dispatch:

jobs:
  core-service:
    name: core-service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.26
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Install dependencies
        run: go work sync

      - name: Build
        run: go build ./services/core/cmd/local/main.go

      - name: Test
        run: go test ./services/core/... -v

  storage-service:
    name: storage-service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.26
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Install dependencies
        run: go work sync

      - name: Build
        run: go build ./services/storage/cmd/local/main.go

      - name: Test
        run: go test ./services/storage/... -v

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '24.5.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install pnpm dependencies
        run: pnpm install
        working-directory: ./services/core/packages/webclient/

      - name: Build web app
        run: pnpm run build
        working-directory: ./services/core/packages/webclient/
